export const LOAD_DATA_PROJET = "projet/loadProjet"
export const ADD_DATA_PROJET = "projet/addProjet"
export const GET_DATA_PROJET_ID = "projet/getProjetId"
export const GET_DATA_LISTE_TICKET_PROJET_ID = "projet/loadListeTicketProjet"
export const UPDATED_DATA_PROJET = "UPDATE_DATA_PROJET"
export const DELETE_DATA_PROJET = "DELETE_DATA_PROJET"